up:
	@docker-compose -f compose.yml --env-file ./env/.env --env-file ./env/.containers.env up

down:
	@docker-compose -f compose.yml --env-file ./env/.env --env-file ./env/.containers.env down

build:
	@docker-compose -f compose.yml --env-file ./env/.env --env-file ./env/.containers.env build